accounts/urls.py
from django.urls import path
from .views import SignUpView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('sign_up/', SignUpView.as_view(), name='sign_up'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
]

dish_composer/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

urlpatterns = [
    path('', include('dishmaker.urls'), name='home_page'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
    path('accounts/', include('accounts.urls')),
    path('api-token-auth/', views.obtain_auth_token, name='api-token-auth'),
    path('parser/', include('scrapy_aizel.urls'))
]

dishmaker/urls.py
from django.urls import path

from .views import DishListView
from .views import DishDetailView, DishDeleteView, DishCreateView, DishUpdateView
from .views import IngredientListView
from .views import IngredientDetailView, IngredientCreateView, IngredientUpdateView, IngredientDeleteView
from .views import OrderListView
from .views import OrderDetailView, OrderCreateView, OrderFromDish, OrderDeleteView, OrderUpdateView

from rest_framework import routers
from dishmaker.api_view import DishViewSet, NoteViewSet, OrderViewSet, IngredientViewSet


app_name = 'dishmaker'

router = routers.SimpleRouter()
router.register(r'api_dishes', DishViewSet)
router.register(r'api_notes', NoteViewSet)
router.register(r'api_ingredients', IngredientViewSet)
router.register(r'api_orders', OrderViewSet)

urlpatterns = [
    path('', DishListView.as_view(), name='index'),
    path('dish/<pk>/', DishDetailView.as_view(), name='dish_page'),
    path('dish_add/add/', DishCreateView.as_view(), name='dish_add'),       # Having an issue when using 'dish/add/
    path('dish/update/<pk>/', DishUpdateView.as_view(), name='dish_update'),
    path('dish/delete/<pk>/', DishDeleteView.as_view(), name='dish_delete'),

    path('form_an_order/<int:dish_id>', OrderFromDish.as_view(), name='order_from_dish'),

    path('order_list/', OrderListView.as_view(), name='order_list_page'),
    path('order_page/<pk>', OrderDetailView.as_view(), name='order_page'),
    path('order_page/add/', OrderCreateView.as_view(), name='order_add'),
    path('order_page/update/<pk>', OrderUpdateView.as_view(), name='order_update'),
    path('order_page/delete/<pk>', OrderDeleteView.as_view(), name='order_delete'),

    path('ingredient/', IngredientListView.as_view(), name='ingredient_list_page'),
    path('ingredient/<pk>', IngredientDetailView.as_view(), name='ingredient'),
    path('ingredient/add/', IngredientCreateView.as_view(), name='ing_add'),
    path('ingredient/update/<pk>/', IngredientUpdateView.as_view(), name='ing_update'),
    path('ingredient/delete/<pk>/', IngredientDeleteView.as_view(), name='ing_delete'),
]

urlpatterns += router.urls

notes/urls.py
from django.urls import path
from .views import NoteOrderListView, NoteDishListView, NoteCreateView


app_name = 'notes'

urlpatterns = [
    path('order_notes/', NoteOrderListView.as_view(), name='order_notes'),
    path('dish_notes/', NoteDishListView.as_view(), name='dish_notes'),
    path('create_note/', NoteCreateView.as_view(), name='create_note'),
]

scrapy_aizel/urls.py
from django.urls import path
from scrapy_aizel.views import AizelParseView, AizelListView


app_name = 'scrapy_aizel'

urlpatterns = [
    path('', AizelParseView.as_view(), name='index'),
    path('clothes_view/', AizelListView.as_view(), name='clothes_list_view'),
]

dishmaker/forms.py
from django import forms
from .models import Dish
from .models import Order
from .models import Ingredient
from .models import IngredientQuantityInDishProxy
from django.forms import inlineformset_factory
from django.forms import ModelForm


class DishForm(ModelForm):

    class Meta:
        model = Dish
        fields = ('name', 'description')


DishIngredientFormSet = inlineformset_factory(
                            Dish, IngredientQuantityInDishProxy,
                            fields=['ingredient_id', 'ingredient_quantity'],
                            extra=2,
                            form=DishForm,
                            min_num=1,
                            validate_min=1,
                        )


class OrderForm(ModelForm):

    class Meta:
        model = Order
        fields = ('dish_id', 'description')


OrderIngredientFormSet = inlineformset_factory(
                            Order, IngredientQuantityInDishProxy,
                            fields=['ingredient_id', 'ingredient_quantity'],
                            extra=0,
                            form=OrderForm
                        )

dishmaker/views.py
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.list import MultipleObjectMixin
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from .models import Dish
from .models import Order
from .models import Ingredient
from .forms import DishIngredientFormSet
from .forms import OrderIngredientFormSet
from django.http import HttpResponseRedirect
from django.db.models import Q
from .utils import many_to_many_igredients_get
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.utils.translation import gettext_lazy as _
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync


class BaseKindaAbstractView(MultipleObjectMixin):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_views'] = ['Privetik']
        return context


class DishListView(ListView, BaseKindaAbstractView):
    template_name = "dishmaker/content/index.html"
    title = _("Recipes list")
    model = Dish

    def get_queryset(self):
        if self.request.method == 'GET':
            if 'search' in self.request.GET:
                searchword = self.request.GET.get('search')
                filter_criteria = Q(name__icontains=searchword) | Q(description__icontains=searchword)
                queryset = self.model.objects.filter(filter_criteria).prefetch_related('ingredients')
            else:
                queryset = self.model.objects.all().prefetch_related('ingredients')
        return queryset

    def get_context_data(self, **kwargs):
        context = BaseKindaAbstractView.get_context_data(self, **kwargs)
        context['title'] = self.title
        recipes = self.object_list
        recipe_list = list()

        for dish in recipes:
            if dish is not None:

                dish_dict = dict()
                dish_dict['dish'] = dish
                dish_dict['ingredients'] = many_to_many_igredients_get(dish)
                recipe_list.append(dish_dict)

        context['recipes_list'] = recipe_list
        # new_one = PageUpdateConsumer()
        return context


class DishDetailView(DetailView):
    template_name = "dishmaker/content/dish_page.html"
    title = "A dish name"  # Should be replaced inside 'get_context_data' with a dish title
    model = Dish

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.name
        context['ingredients'] = many_to_many_igredients_get(self.object)
        context['model_type'] = self.model.__name__

        return context


class DishCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):

    permission_required = "dishmaker.add_dish"

    model = Dish
    title = _("Add a Dish")
    fields = ['name', 'description']
    success_url = reverse_lazy('dishmaker:index')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.object = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        if self.request.POST:
            # print(self.request.POST)
            context['dish_formset'] = DishIngredientFormSet(self.request.POST)
        else:
            context['dish_formset'] = DishIngredientFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['dish_formset']

        if form.is_valid():

            if formset.is_valid():
                self.object = form.save(commit=False)
                self.object.author = self.request.user
                self.object.save()
                formset.instance = self.object
                formset.save()
                layer = get_channel_layer()
                async_to_sync(layer.group_send)(
                    'main_page_viewers',
                    {
                        'type': 'chat_message',
                        'message': 'update_page'
                    }
                )
                # async_to_sync(layer.group_send)('events', {'type': 'test'})
                print('should trigger')
                return super().form_valid(form)
            else:
                return redirect(reverse('dishmaker:dish_add'))


class DishUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):

    permission_required = "dishmaker.change_dish"

    model = Dish
    title = _("Update a Dish")
    fields = ['name', 'description']
    success_url = reverse_lazy('dishmaker:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['dish_formset'] = DishIngredientFormSet(self.request.POST, instance=self.object)
        else:
            context['dish_formset'] = DishIngredientFormSet(instance=self.object)
            context['title'] = self.title
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['dish_formset']

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class DishDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):

    permission_required = "dishmaker.delete_dish"

    model = Dish
    title = _("Remove a dish")
    success_url = reverse_lazy('dishmaker:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class IngredientListView(PermissionRequiredMixin, LoginRequiredMixin, ListView, BaseKindaAbstractView):

    permission_required = "dishmaker.view_ingredient"

    template_name = "dishmaker/content/ingredient_list.html"
    title = _("Ingredient list")
    model = Ingredient

    def get_context_data(self, **kwargs):
        context = BaseKindaAbstractView.get_context_data(self, **kwargs)
        context['title'] = self.title
        context['ingredients'] = self.object_list
        return context


class IngredientDetailView(PermissionRequiredMixin, LoginRequiredMixin, DetailView):

    permission_required = "dishmaker.view_ingredient"

    template_name = "dishmaker/content/ingredient_page.html"
    model = Ingredient

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.name
        # context['categories'] = list_categories(storeId)
        return context


class IngredientCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):

    permission_required = "dishmaker.add_ingredient"

    model = Ingredient
    title = _("Add Ingredient")
    fields = ['name', 'description']
    success_url = reverse_lazy('dishmaker:ingredient_list_page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class IngredientUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):

    permission_required = "dishmaker.change_ingredient"

    model = Ingredient
    title = _("Update Ingredient")
    fields = ['name', 'description']
    success_url = reverse_lazy('dishmaker:ingredient_list_page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class IngredientDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):

    permission_required = "dishmaker.delete_ingredient"

    model = Ingredient
    title = _("Remove ingredient")
    success_url = reverse_lazy('dishmaker:ingredient_list_page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class OrderDetailView(LoginRequiredMixin, DetailView):
    template_name = "dishmaker/content/order_page.html"
    title = "A dish name"   # Should be replaced inside 'get_context_data' with a dish title
    model = Order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Order: ' + str(self.object.id)
        '''
            In case there will be repetitions of ingredients, we need to split procedure into two parts
        '''
        ing_list = [
            (ing.ingredient_id.name, ing.ingredient_quantity) for ing in self.object.order.all()
        ]
        context['ingredients'] = dict()
        context['model_type'] = self.model.__name__
        for ing in ing_list:
            if ing[0] not in context['ingredients']:
                value = ing[1]
            else:
                value = context['ingredients'][ing[0]] + ing[1]
            context['ingredients'][ing[0]] = value

        return context


class OrderFromDish(LoginRequiredMixin, TemplateView):
    template_name = "dishmaker/content/order_from_dish.html"
    title = "A dish name"   # Should be replaced inside 'get_context_data' with a dish title
    model = Dish

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        if 'dish_id' in self.kwargs:
            dish = self.model.objects.filter(id=self.kwargs['dish_id']).first()
            context['title'] = dish.name
            context['description'] = dish.description

            '''
                In case there will be repetitions of ingredients, we need to split procedure into two parts
            '''
            ing_list = [

dishmaker/templates/dishmaker/base.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
              integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
              crossorigin="anonymous">

        <link href="{%static 'dishmaker/header.css'%}" rel="stylesheet">
        <link href="{%static 'dishmaker/content_header.css'%}" rel="stylesheet">
        <title>{% trans "Restaurantio" %}</title>
    </head>
    <body>
    {% include "dishmaker/site_header.html" %}
    {% block content_base %}
    {% endblock %}

    {% comment %}




    {#
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    #}
    {% endcomment %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

dishmaker/templates/dishmaker/dish_confirm_delete.html
{% extends "dishmaker/content/content_base.html" %}
{% load i18n %}
{% block inner_context %}
    <form method="post">
        {% csrf_token %}
        {{ form.errors }}
        <h3> {% trans "Please confirm deletion of" %} "{{ object }}" </h3>
        <input class="btn btn-primary crud-button" type="submit" value="{% trans 'Confirm' %}">
        <a href="{% url 'dishmaker:dish_page' object.id %}" type="button" class="btn btn-primary crud-button">
            {% trans "Decline" %}
        </a>
    </form>
{% endblock %}

dishmaker/templates/dishmaker/dish_form.html
{% extends "dishmaker/content/content_base.html" %}
{% load i18n %}
{% block inner_context %}

    <br>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}

        <table class="table">
            {{ dish_formset.management_form }}
            {% for form_instance in dish_formset.forms %}
                {{ form_instance }}
            {% endfor %}
        </table>
        <input type="submit" value="{% trans 'Save' %}">
    </form>
    <br>
    <br>

{% endblock %}

dishmaker/templates/dishmaker/ingredient_confirm_delete.html
{% extends "dishmaker/content/content_base.html" %}
{% load i18n %}
{% block inner_context %}
    <form method="post">
        {% csrf_token %}
        {{ form.errors }}
        <h3> {% trans "Please confirm deletion of" %} "{{ object }}" </h3>
        <input class="btn btn-primary crud-button" type="submit" value="{% trans 'Confirm' %}">
        <a href="{% url 'dishmaker:ingredient' object.id %}" type="button" class="btn btn-primary crud-button">
            {% trans "Decline" %}
        </a>
    </form>
{% endblock %}

dishmaker/templates/dishmaker/ingredient_form.html
{% extends "dishmaker/content/content_base.html" %}
{% load i18n %}
{% block inner_context %}
    <div class="row ">

        <div class="col-9 offset-1 content-main">
            <br>
            <p> {{description}} </p>
            <form method="POST">
                {% csrf_token %}
                {{ form.errors }}
                <h5> {% trans "Ingredients name" %}: </h5>
                {{ form.name }}
                <br>
                <h5> {% trans "Insert description (optionally)" %} </h5>
                {{ form.description }}
                <br>
                <br>
                <input class="btn btn-primary" type="submit" value="{% trans 'Save' %}">
            </form>
            <br>
            <hr>
        </div>
    </div>

{% endblock %}

dishmaker/templates/dishmaker/order_confirm_delete.html
{% extends "dishmaker/content/content_base.html" %}
{% load i18n %}
{% block inner_context %}
    <form method="post">
        {% csrf_token %}
        {{ form.errors }}
        <h3> {% trans "Please confirm deletion of" %} "{{ object }}" </h3>
        <input class="btn btn-primary crud-button" type="submit" value="{% trans 'Confirm' %}">
        <a href="{% url 'dishmaker:order_page' object.id %}" type="button" class="btn btn-primary crud-button">
            {% trans "Decline" %}
        </a>
    </form>
{% endblock %}

dishmaker/templates/dishmaker/order_form.html
{% extends "dishmaker/content/content_base.html" %}
{% load i18n %}
{% block inner_context %}

    <br>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}

        <table class="table">
            {{ order_formset.management_form }}
            {% for form_instance in order_formset.forms %}
                {{ form_instance }}
            {% endfor %}
        </table>
        <input type="submit" value="{% trans 'Save' %}">
    </form>
    <br>
    <br>

{% endblock %}

dishmaker/templates/dishmaker/site_header.html
{% load i18n %}

<container>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dishmaker:index' %}">{% trans "Home page" %}</a>
            </li>
            {% if user.is_authenticated and user.is_active and user.is_staff %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'notes:order_notes' %}">{% trans "Order note list" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'notes:dish_notes' %}">{% trans "Dish note list" %}</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'scrapy_aizel:index' %}"><strong>Scrapy</strong></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'scrapy_aizel:clothes_list_view' %}">
                    <strong>
                        Scrapy items list
                    </strong>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav rigth-sequence ml-auto">
            <li class="nav-item" >
                <form action="{% url 'set_language' %}" style="width:300px; padding-top:5px;" method="post">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    <select name="language">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                {{ language.name_local }} ({{ language.code }})
                            </option>
                        {% endfor %}
                    </select>
                           <!--worst practice ever, im sorry, im in hurry-->
                    <input type="submit" class="nav-item log-button crud-button"
                           style="padding:0px; margin:0px; margin-left:10px; width:120px;"
                           value="{% trans 'Set' %}">
                </form>
            </li>
            {% if user.is_authenticated %}
                <span class="navbar-text">
                    {% trans "Hello" %},
                </span>
                <span class="navbar-text name">
                    {{user.username}}
                </span>
                <li class="nav-item log-button ">
                    <a class="text-right nav-link" href="{% url 'accounts:logout' %}">{% trans "Logout" %}</a>
                </li>
            {% else %}
                <li class="nav-item log-button ">
                    <a class="text-right nav-link" href="{% url 'accounts:sign_up' %}">{% trans "Sing Up" %}</a>
                </li>
                <li class="nav-item log-button ">
                    <a class="text-right nav-link" href="{% url 'accounts:login' %}">{% trans "Login" %}</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    {% if user.is_superuser and user.is_authenticated %}
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dishmaker:dish-list' %}"> Dish api</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dishmaker:order-list' %}">Order api</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dishmaker:ingredient-list' %}">Ingredients api</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dishmaker:noteditem-list' %}">Notes api</a>
            </li>
        </ul>
    </nav>
    {% endif %}
</container>