dish_composer/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

urlpatterns = [
    path('', include('dishmaker.urls'), name='home_page'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
    path('accounts/', include('accounts.urls')),
    path('api-token-auth/', views.obtain_auth_token, name='api-token-auth'),
    path('parser/', include('scrapy_aizel.urls'))
]

dishmaker/urls.py
from django.urls import path

from .views import DishListView
from .views import DishDetailView, DishDeleteView, DishCreateView, DishUpdateView
from .views import IngredientListView
from .views import IngredientDetailView, IngredientCreateView, IngredientUpdateView, IngredientDeleteView
from .views import OrderListView
from .views import OrderDetailView, OrderCreateView, OrderFromDish, OrderDeleteView, OrderUpdateView

from rest_framework import routers
from dishmaker.api_view import DishViewSet, NoteViewSet, OrderViewSet, IngredientViewSet


app_name = 'dishmaker'

router = routers.SimpleRouter()
router.register(r'api_dishes', DishViewSet)
router.register(r'api_notes', NoteViewSet)
router.register(r'api_ingredients', IngredientViewSet)
router.register(r'api_orders', OrderViewSet)

urlpatterns = [
    path('', DishListView.as_view(), name='index'),
    path('dish/<pk>/', DishDetailView.as_view(), name='dish_page'),
    path('dish_add/add/', DishCreateView.as_view(), name='dish_add'),       # Having an issue when using 'dish/add/
    path('dish/update/<pk>/', DishUpdateView.as_view(), name='dish_update'),
    path('dish/delete/<pk>/', DishDeleteView.as_view(), name='dish_delete'),

    path('form_an_order/<int:dish_id>', OrderFromDish.as_view(), name='order_from_dish'),

    path('order_list/', OrderListView.as_view(), name='order_list_page'),
    path('order_page/<pk>', OrderDetailView.as_view(), name='order_page'),
    path('order_page/add/', OrderCreateView.as_view(), name='order_add'),
    path('order_page/update/<pk>', OrderUpdateView.as_view(), name='order_update'),
    path('order_page/delete/<pk>', OrderDeleteView.as_view(), name='order_delete'),

    path('ingredient/', IngredientListView.as_view(), name='ingredient_list_page'),
    path('ingredient/<pk>', IngredientDetailView.as_view(), name='ingredient'),
    path('ingredient/add/', IngredientCreateView.as_view(), name='ing_add'),
    path('ingredient/update/<pk>/', IngredientUpdateView.as_view(), name='ing_update'),
    path('ingredient/delete/<pk>/', IngredientDeleteView.as_view(), name='ing_delete'),
]

urlpatterns += router.urls

notes/urls.py
from django.urls import path
from .views import NoteOrderListView, NoteDishListView, NoteCreateView


app_name = 'notes'

urlpatterns = [
    path('order_notes/', NoteOrderListView.as_view(), name='order_notes'),
    path('dish_notes/', NoteDishListView.as_view(), name='dish_notes'),
    path('create_note/', NoteCreateView.as_view(), name='create_note'),
]

dishmaker/forms.py
from django import forms
from .models import Dish
from .models import Order
from .models import Ingredient
from .models import IngredientQuantityInDishProxy
from django.forms import inlineformset_factory
from django.forms import ModelForm


class DishForm(ModelForm):

    class Meta:
        model = Dish
        fields = ('name', 'description')


DishIngredientFormSet = inlineformset_factory(
                            Dish, IngredientQuantityInDishProxy,
                            fields=['ingredient_id', 'ingredient_quantity'],
                            extra=2,
                            form=DishForm,
                            min_num=1,
                            validate_min=1,
                        )


class OrderForm(ModelForm):

    class Meta:
        model = Order
        fields = ('dish_id', 'description')


OrderIngredientFormSet = inlineformset_factory(
                            Order, IngredientQuantityInDishProxy,
                            fields=['ingredient_id', 'ingredient_quantity'],
                            extra=0,
                            form=OrderForm
                        )

dishmaker/views.py
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.list import MultipleObjectMixin
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from .models import Dish
from .models import Order
from .models import Ingredient
from .forms import DishIngredientFormSet
from .forms import OrderIngredientFormSet
from django.http import HttpResponseRedirect
from django.db.models import Q
from .utils import many_to_many_igredients_get
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.utils.translation import gettext_lazy as _
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync


class BaseKindaAbstractView(MultipleObjectMixin):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_views'] = ['Privetik']
        return context


class DishListView(ListView, BaseKindaAbstractView):
    template_name = "dishmaker/content/index.html"
    title = _("Recipes list")
    model = Dish

    def get_queryset(self):
        if self.request.method == 'GET':
            if 'search' in self.request.GET:
                searchword = self.request.GET.get('search')
                filter_criteria = Q(name__icontains=searchword) | Q(description__icontains=searchword)
                queryset = self.model.objects.filter(filter_criteria).prefetch_related('ingredients')
            else:
                queryset = self.model.objects.all().prefetch_related('ingredients')
        return queryset

    def get_context_data(self, **kwargs):
        context = BaseKindaAbstractView.get_context_data(self, **kwargs)
        context['title'] = self.title
        recipes = self.object_list
        recipe_list = list()

        for dish in recipes:
            if dish is not None:

                dish_dict = dict()
                dish_dict['dish'] = dish
                dish_dict['ingredients'] = many_to_many_igredients_get(dish)
                recipe_list.append(dish_dict)

        context['recipes_list'] = recipe_list
        # new_one = PageUpdateConsumer()
        return context


class DishDetailView(DetailView):
    template_name = "dishmaker/content/dish_page.html"
    title = "A dish name"  # Should be replaced inside 'get_context_data' with a dish title
    model = Dish

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.name
        context['ingredients'] = many_to_many_igredients_get(self.object)
        context['model_type'] = self.model.__name__

        return context


class DishCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):

    permission_required = "dishmaker.add_dish"

    model = Dish
    title = _("Add a Dish")
    fields = ['name', 'description']
    success_url = reverse_lazy('dishmaker:index')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.object = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        if self.request.POST:
            # print(self.request.POST)
            context['dish_formset'] = DishIngredientFormSet(self.request.POST)
        else:
            context['dish_formset'] = DishIngredientFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['dish_formset']

        if form.is_valid():

            if formset.is_valid():
                self.object = form.save(commit=False)
                self.object.author = self.request.user
                self.object.save()
                formset.instance = self.object
                formset.save()
                layer = get_channel_layer()
                async_to_sync(layer.group_send)(
                    'main_page_viewers',
                    {
                        'type': 'chat_message',
                        'message': 'update_page'
                    }
                )
                # async_to_sync(layer.group_send)('events', {'type': 'test'})
                print('should trigger')
                return super().form_valid(form)
            else:
                return redirect(reverse('dishmaker:dish_add'))


class DishUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):

    permission_required = "dishmaker.change_dish"

    model = Dish
    title = _("Update a Dish")
    fields = ['name', 'description']
    success_url = reverse_lazy('dishmaker:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['dish_formset'] = DishIngredientFormSet(self.request.POST, instance=self.object)
        else:
            context['dish_formset'] = DishIngredientFormSet(instance=self.object)
            context['title'] = self.title
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['dish_formset']

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class DishDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):

    permission_required = "dishmaker.delete_dish"

    model = Dish
    title = _("Remove a dish")
    success_url = reverse_lazy('dishmaker:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class IngredientListView(PermissionRequiredMixin, LoginRequiredMixin, ListView, BaseKindaAbstractView):

    permission_required = "dishmaker.view_ingredient"

    template_name = "dishmaker/content/ingredient_list.html"
    title = _("Ingredient list")
    model = Ingredient

    def get_context_data(self, **kwargs):
        context = BaseKindaAbstractView.get_context_data(self, **kwargs)
        context['title'] = self.title
        context['ingredients'] = self.object_list
        return context


class IngredientDetailView(PermissionRequiredMixin, LoginRequiredMixin, DetailView):

    permission_required = "dishmaker.view_ingredient"

    template_name = "dishmaker/content/ingredient_page.html"
    model = Ingredient

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.name
        # context['categories'] = list_categories(storeId)
        return context


class IngredientCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):

    permission_required = "dishmaker.add_ingredient"

    model = Ingredient
    title = _("Add Ingredient")
    fields = ['name', 'description']
    success_url = reverse_lazy('dishmaker:ingredient_list_page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class IngredientUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):

    permission_required = "dishmaker.change_ingredient"

    model = Ingredient
    title = _("Update Ingredient")
    fields = ['name', 'description']
    success_url = reverse_lazy('dishmaker:ingredient_list_page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class IngredientDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):

    permission_required = "dishmaker.delete_ingredient"

    model = Ingredient
    title = _("Remove ingredient")
    success_url = reverse_lazy('dishmaker:ingredient_list_page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class OrderDetailView(LoginRequiredMixin, DetailView):
    template_name = "dishmaker/content/order_page.html"
    title = "A dish name"   # Should be replaced inside 'get_context_data' with a dish title
    model = Order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Order: ' + str(self.object.id)
        '''
            In case there will be repetitions of ingredients, we need to split procedure into two parts
        '''
        ing_list = [
            (ing.ingredient_id.name, ing.ingredient_quantity) for ing in self.object.order.all()
        ]
        context['ingredients'] = dict()
        context['model_type'] = self.model.__name__
        for ing in ing_list:
            if ing[0] not in context['ingredients']:
                value = ing[1]
            else:
                value = context['ingredients'][ing[0]] + ing[1]
            context['ingredients'][ing[0]] = value

        return context


class OrderFromDish(LoginRequiredMixin, TemplateView):
    template_name = "dishmaker/content/order_from_dish.html"
    title = "A dish name"   # Should be replaced inside 'get_context_data' with a dish title
    model = Dish

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        if 'dish_id' in self.kwargs:
            dish = self.model.objects.filter(id=self.kwargs['dish_id']).first()
            context['title'] = dish.name
            context['description'] = dish.description

            '''
                In case there will be repetitions of ingredients, we need to split procedure into two parts
            '''
            ing_list = [

dishmaker/templates/dishmaker/content/content_base.html
{% extends "dishmaker/base.html" %}

{% block content_base %}
{% include "dishmaker/content/content_header.html" %}
    <div class="container">
        {% include "dishmaker/content/content_navbar.html" %}
        <div class="title">
             {{ title }}
        </div>
        {% block inner_context %}
        {% endblock %}
    </div>
{% endblock %}

dishmaker/templates/dishmaker/content/content_header.html
{% load i18n %}
<div class="content-header">
    <div class="container">
        <h1 class="blog-title">{% trans "Restaurantio" %}</h1>
        <p class="lead blog-description">{% trans "A super uncommon order site made on top of a blog" %}</p>
    </div>
</div>

dishmaker/templates/dishmaker/content/content_navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dishmaker:index' %}">{% trans "Dish list" %}</a>
      </li>
      {% if user.is_authenticated and user.is_active and user.is_staff %}
      <li class="nav-item">
        <a class="nav-link icon-add" href="{% url 'dishmaker:dish_add' %}"><i class="fas fa-plus-square"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dishmaker:ingredient_list_page' %}">{% trans "Ingredient list" %}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link icon-add" href="{% url 'dishmaker:ing_add' %}"><i class="fas fa-plus-square"></i></a>
      </li>
    {% endif %}
    {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dishmaker:order_list_page' %}">{% trans "Order list" %}</a>
      </li>
    {% endif %}
    </ul>
    <form method='GET' action=""  class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search"
             placeholder="{% trans 'Search' %}"
             aria-label="{% trans 'Search' %}" name="search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{% trans 'Search' %}</button>
    </form>
  </div>
</nav>

dishmaker/templates/dishmaker/content/dish_page.html
{% extends "dishmaker/content/content_base.html" %}
{% load i18n %}
{% block inner_context %}

    <div class="row ">

        <div class="col-9 offset-1 content-main">
            <h4> {% trans "Desctiption" %}: </h4>
            <hr>
            <p> {{object.description}} </p>
            <h3>{% trans 'Consists of' %}: </h3>
            <ul style="list-style-type:circle;">
                {% for name, quantity in ingredients.items %}
                    <li> {{name}} : {{quantity}} </li>
                {% endfor %}
            </ul>
            <p class="blog-post-meta">{% trans "Added on" %} {{object.created_on}}, {% trans "Chef" %}:
                <a href="#">{{object.author}}</a>
            </p>
            <hr>

            {% if user.is_authenticated %}
            <a class="btn btn-primary" type="button" href="{% url 'dishmaker:order_from_dish' object.id %}">
                {% trans "Make an order" %}
            </a>
            {% endif %}
        </div>
        {% if user.is_authenticated and user.is_active and user.is_staff %}
        <div class="col-2">
            <div class="row">
                <a href="{% url 'dishmaker:dish_update' object.id %}" type="button" class="btn btn-primary crud-button">
                    {% trans "Edit" %}
                </a>
            </div>
            <div class="row">
                <a href="{% url 'dishmaker:dish_delete' object.id %}" type="button" class="btn btn-primary crud-button">
                    {% trans "Delete" %}
                </a>
            </div>
            <br>
            <div class="row">
                <form action="{% url 'notes:create_note' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" value="{{ model_type }}" name="model_type">
                    <input type="hidden" value="{{ object.id }}" name="model_id">
                    <button class="btn btn-primary crud-button" type="submit">
                        {% trans "Note" %}
                    </button>
                </form>
            </div>
        </div>
        {% endif %}
    </div>

{% endblock %}

dishmaker/templates/dishmaker/content/index.html
{% extends "dishmaker/content/content_base.html" %}
{% load i18n %}

{% block inner_context %}

<script>
    var socketUpdater = new WebSocket(
        'ws://' + window.location.host +
        '/ws/');

    socketUpdater.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        if (message == 'update_page') {
            location.reload();
        }
    };

    socketUpdater.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };
</script>
<div class="row ">
    <div class="col-9 offset-1 content-main">
        {% for dish_comp_dict in recipes_list %}
        <div class="blog-post">
            <hr>
            <h3 class="blog-post-title">
                <a href="{% url 'dishmaker:dish_page' dish_comp_dict.dish.id %}">
                {{dish_comp_dict.dish.name}}
                </a>
            </h3>
            <hr>
            <p class="blog-post-meta"> {% trans "Chef" %}: <a href="#">{{dish_comp_dict.dish.author}}</a></p>
            <h4> {% trans "Desctiption" %}: </h4>
            <p> {{dish_comp_dict.dish.description}} </p>
            <h5> {% trans "Consists of" %}: </h5>
            <ul style="list-style-type:circle;">
                {% for ing, quantity in dish_comp_dict.ingredients.items %}
                    <li> {{ing}} : {{quantity}} </li>
                {% endfor %}
            </ul>
        </div>
        <hr>
        {% endfor %}
      </div><!-- /.row -->

</div>
{% endblock %}

dishmaker/templates/dishmaker/content/ingredient_list.html
{% extends "dishmaker/content/content_base.html" %}
{% load i18n %}
{% block inner_context %}

    <div class="row ">

        <div class="col-9 offset-1 content-main">
            {% for ing in ingredients %}
                <hr>
                    <h2> <a href="{% url 'dishmaker:ingredient' ing.id %}"> {{ing.name}} </a> </h2>

                    </a>
                <br>
                <p> {{ing.description}} </p>
            {% endfor %}
            <hr>

        </div>
    </div>

{% endblock %}

dishmaker/templates/dishmaker/content/ingredient_page.html
{% extends "dishmaker/content/content_base.html" %}
{% load i18n %}
{% block inner_context %}

    <div class="row ">

        <div class="col-9 offset-1 content-main">
            <h5> {% trans "Desctiption" %}: </h5>

            <p> {{object.description}} </p>
            </ul>

        </div>
      {% if user.is_authenticated and user.is_active and user.is_staff %}
        <div class="col-2">
            <div class="row">
                <a href="{% url 'dishmaker:ing_update' object.id %}" type="button" class="btn btn-primary crud-button">
                    {% trans "Edit" %}
                </a>
            </div>
            <div class="row">
                <a href="{% url 'dishmaker:ing_delete' object.id %}" type="button" class="btn btn-primary crud-button">
                    {% trans "Delete" %}
                </a>
            </div>
        </div>
      {% endif %}
    </div>

{% endblock %}

dishmaker/templates/dishmaker/content/order_from_dish.html
{% extends "dishmaker/content/content_base.html" %}
{% load i18n %}
{% block inner_context %}

    <div class="row ">

        <div class="col-9 offset-1 content-main">
            <br>
            {% with val=dish_id %}
            <form action="{% url 'dishmaker:order_add' %} " method="POST">
                {% endwith %}
                {% csrf_token %}
                <h5> {% trans "An order for" %} {{object.dish_id}}</h5>
                <h5> Please select ingredients to insert into your dish: </h5>
                <ul style="list-style-type:circle;">
                    {% for name, quantity in ingredients.items %}
                        <li>
                            <input id="{{name}}" type="number" name="{{name}}" value="{{quantity}}" min="1">
                            <label for="{{name}}">{{name}}</label>
                        </li>
                    {% endfor %}
                    <input type="hidden" value="{{ dish_id }}" name="dish_id">
                </ul>

                <h5> {% trans "You may also add a decription to your order" %} </h5>
                <textarea name="description" cols="60" rows="3"></textarea>
                <br>
                <br>
                <input class="btn btn-primary" type="submit" value="{% trans 'Confirm' %}">
            </form>
            <br>
            <hr>
        </div>
    </div>

{% endblock %}

dishmaker/templates/dishmaker/content/order_list.html
{% extends "dishmaker/content/content_base.html" %}
{% load i18n %}
{% block inner_context %}

    <div class="row ">

        <div class="col-9 offset-1 content-main">
            {% for order_dict in order_list %}
                {% if order_dict.order.is_active %}
                <div class="blog-post">
                    <hr>
                    <h4 class="blog-post-title">
                        <a href="{% url 'dishmaker:order_page' order_dict.order.id %}">
                        {% trans "Order" %}: {{order_dict.order.id}} -- {{order_dict.order.dish_id.name}}--
                        </a>
                    </h4>
                    <hr>
                    <p class="blog-post-meta"> {% trans "Ordered by" %} <a href="#">{{order_dict.order.author}}</a></p>
                    <h4> {% trans "Desctiption" %}: </h4>
                    <p> {{order_dict.order.description}} </p>
                    <h5> {% trans "Consists of" %}: </h5>
                    <ul style="list-style-type:circle;">
                        {% for ing, quantity in order_dict.ingredients.items %}
                            <li> {{ing}} : {{quantity}} </li>
                        {% endfor %}
                    </ul>
                    <hr>
                </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>

{% endblock %}

dishmaker/templates/dishmaker/content/order_page.html
{% extends "dishmaker/content/content_base.html" %}
{% load i18n %}
{% block inner_context %}

    <div class="row ">
        <div class="col-9 offset-1 content-main">
            <h4> {% trans "An order for" %} '{{object.dish_id.name}}' </h4>
            <h5> {% trans "That consists of" %}: </h5>
            <ul style="list-style-type:circle;">
                {% for name, quantity in ingredients.items %}
                    <li> {{name}} : {{quantity}} </li>
                {% endfor %}
            </ul>
            <p class="blog-post-meta">{% blocktrans with date=object.created_on %}Ordered on {{date}}, by {%endblocktrans%}
                <a href="#">{{object.author}}</a></p>
            <hr>
        </div>
        {% if user.is_authenticated and user.is_active and user.is_staff %}
        <div class="col-2">
            <div class="row">
                <a href="{% url 'dishmaker:order_update' object.id %}" type="button" class="btn btn-primary crud-button">
                    {% trans "Edit" %}
                </a>
            </div>
            <div class="row">
                <a href="{% url 'dishmaker:order_delete' object.id %}" type="button" class="btn btn-primary crud-button">
                    {% trans "Delete" %}
                </a>
            </div>
            <br>
            <div class="row">
                <form action="{% url 'notes:create_note' %}" method="get">
                    <input type="hidden" value="{{ model_type }}" name="model_type">
                    <input type="hidden" value="{{ object.id }}" name="model_id">
                    <button class="btn btn-primary crud-button" type="submit">
                        {% trans "Note" %}
                    </button>
                </form>
            </div>
        </div>
        {% endif %}
    </div>

{% endblock %}